env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  no-tabs:
    - warn
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
